src/meltano/api/auth.py
from authlib.flask.client import OAuth as OAuthClient
from flask import Blueprint, url_for, redirect, current_app
from flask_security import current_user, AnonymousUser
from flask_security.utils import login_user, do_flash, url_for_security
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.exc import NoResultFound
from .security import users
from .models import db, OAuth
from meltano.core.utils import compose

import json
import base64
import gitlab


class OAuthError(Exception):
    pass


def base64_pad(s):
    padding = 4 - (len(s) % 4)
    return s + ("=" * padding)


jwt_decode = compose(json.loads, base64.urlsafe_b64decode, base64_pad)


def setup_oauth(app):
    oauth = OAuthClient(app)
    oauth.register(
        "gitlab",
        access_token_url="https://gitlab.com/oauth/token",
        client_kwargs={"scope": "openid read_user"},
        authorize_url="https://gitlab.com/oauth/authorize",
    )

    oauthBP = Blueprint("OAuth", __name__, url_prefix="/oauth")

    @oauthBP.route("/login")
    def login():
        redirect_uri = url_for(".authorize", _external=True)
        return oauth.gitlab.authorize_redirect(redirect_uri)

    @oauthBP.route("/authorize")
    def authorize():
        token = oauth.gitlab.authorize_access_token()

        try:
            identity = gitlab_token_identity(token)
            login_user(identity.user, remember=False)

            return redirect(url_for("root.analyze"))
        except OAuthError as e:
            do_flash(str(e))
            return redirect(url_for_security("login"))

    app.register_blueprint(oauthBP)


def gitlab_token_identity(token):
    # TODO: having to do another GET to grab the user info
    #       is subpar, but the returned JWT lacks the user's email
    #
    # It seems like validating the JWT token is not
    # currently working as the GitLab JWKs endpoint is unstable
    # See https://gitlab.com/gitlab-com/support-forum/issues/3666
    client = gitlab.Gitlab("http://gitlab.com", oauth_token=token["access_token"])
    client.auth()

    if client.user.state != "active":
        raise OAuthError("This account is not active.")

    user = current_user.is_authenticated and current_user
    token_user = users.get_user(client.user.email)

    identity = None
    try:
        identity = (
            db.session.query(OAuth)
            .options(joinedload(OAuth.user))
            .filter_by(provider_id="gitlab", provider_user_id=client.user.id)
            .one()
        )
    except NoResultFound:
        identity = OAuth.from_token("gitlab", client.user.id, token)

    if current_user.is_authenticated:
        # map the identity to the current_user
        identity.user = current_user
        db.session.add(identity)
    elif not token_user:
        # no user has claimed this email yet
        # reserve it
        token_user = users.create_user(email=client.user.email)
        identity.user = token_user
        db.session.add(identity)
    elif identity.user == token_user:
        # we have a match, a user with this email and identity
        # TODO: update the identity if need be
        pass
    else:
        raise OAuthError("This identity is already claimed by another user.")

    db.session.commit()
    return identity

src/meltano/api/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  {% set field_class = kwargs.pop("field_class", "input") %}
  {% set label_class = kwargs.pop("label_class", "label is-small") %}
  <div class="field">
    {{ field.label(class_=label_class)}}
    <div class="control">
      {{ field(class_=field_class, **kwargs)|safe }}
    </div>
    {% if field.errors %}
      <ul class="help">
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endmacro %}

{% macro render_field(field) %}
  {% set cls = kwargs.pop("class_", "input") %}
  <p class="control">{{ field(class_=cls, **kwargs)|safe }}</p>
{% endmacro %}

{% macro title(text) %}
  <h1 style="margin-bottom: 1em;" class="has-text-grey-light has-text-weight-light has-text-centered">{{ text|safe }}</h1>
{% endmacro %}

{% macro render_button(field) %}
  {% set cls = kwargs.pop("class_", "button") %}
  <p class="control">{{ field(class_=cls, **kwargs)|safe }}</p>
{% endmacro %}

src/meltano/api/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>{{ _('Menu') }}</h2>
<ul>
  <li>
    <a class_="button is-link" href="{{ url_for('OAuth.login') }}">Login with GitLab</a>
  </li>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Register') }}</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password') }}</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">{{ _('Confirm account') }}</a></li>
  {% endif %}
</ul>
{% endif %}

src/meltano/api/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}

src/meltano/api/templates/security/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
  {%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{ title|default }}{% endblock title %}</title>

      {%- block metas %}
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {%- endblock metas %}

      {%- block styles %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
      {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body style="margin-top: 6rem" {% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
      {% block navbar %}
      {%- endblock navbar %}
      <div class="columns is-centered is-vcentered">
        <div class="column is-one-third">
          <figure style="margin: 1rem 2rem;" class="image">
            <img src="/static/meltano-logo.png">
          </figure>
          <div class="box">
          {% block content -%}
          {%- endblock content %}
          </div>
          <div class="box">
          {% include "security/_menu.html" %}
          </div>
        </div>
      </div>
      {% block scripts %}
      {%- endblock scripts %}
    {%- endblock body %}
  </body>
  {%- endblock html %}
</html>
{% endblock doc -%}

src/meltano/api/templates/security/change_password.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
{% include "security/_messages.html" %}
{{ title(_('Change password')) }}
<form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
  {{ change_password_form.hidden_tag() }}
  {{ render_field_with_errors(change_password_form.password) }}
  {{ render_field_with_errors(change_password_form.new_password) }}
  {{ render_field_with_errors(change_password_form.new_password_confirm) }}
  {{ change_password_form.submit(class_="button is-link") }}
</form>
{% endblock %}

src/meltano/api/templates/security/forgot_password.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, title %}

{% block content %}
{% include "security/_messages.html" %}
{{ title(_('Send password reset instructions')) }}
<form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
  {{ forgot_password_form.hidden_tag() }}
  {{ render_field_with_errors(forgot_password_form.email) }}
  {{ render_field(forgot_password_form.submit, class_="button is-link") }}
</form>
{% endblock %}

src/meltano/api/templates/security/login_user.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, title %}

{% block content %}
{% include "security/_messages.html" %}

{{ title(_("Login")) }}
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember, field_class="checkbox") }}
  {{ render_field(login_user_form.submit, class_="button is-link") }}
</form>

{% endblock %}

src/meltano/api/templates/security/register_user.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
{% include "security/_messages.html" %}
{{ title(_('Register')) }}
<form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
  {{ register_user_form.hidden_tag() }}
  {{ render_field_with_errors(register_user_form.email) }}
  {{ render_field_with_errors(register_user_form.password) }}
  {% if register_user_form.password_confirm %}
    {{ render_field_with_errors(register_user_form.password_confirm) }}
  {% endif %}
  {{ render_field(register_user_form.submit, class_="button is-link") }}
</form>
{% endblock %}

src/meltano/api/templates/security/reset_password.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
{% include "security/_messages.html" %}
{{ title(_('Reset password')) }}
<form action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form">
  {{ reset_password_form.hidden_tag() }}
  {{ render_field_with_errors(reset_password_form.password) }}
  {{ render_field_with_errors(reset_password_form.password_confirm) }}
  {{ render_field(reset_password_form.submit, class_="button is-link") }}
</form>
{% endblock %}

src/meltano/api/templates/security/send_confirmation.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
{% include "security/_messages.html" %}
{{ title(_('Resend confirmation instructions')) }}
<form action="{{ url_for_security('send_confirmation') }}" method="POST" name="send_confirmation_form">
  {{ send_confirmation_form.hidden_tag() }}
  {{ render_field_with_errors(send_confirmation_form.email) }}
  {{ render_field(send_confirmation_form.submit, class_="button is-link") }}
</form>
{% endblock %}

src/meltano/api/templates/security/send_login.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
{% include "security/_messages.html" %}
{{ title(_('Login')) }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="send_login_form">
  {{ send_login_form.hidden_tag() }}
  {{ render_field_with_errors(send_login_form.email) }}
  {{ render_field(send_login_form.submit, class_="button is-link") }}
</form>
{% endblock %}